permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Iki Hiyori
  email: 1002877803@qq.com
  link: http://hiyori.cn
  weibo: http://weibo.com/1002877803
  github: http://github.com/IkiHiyori
  music: http://site.douban.com/
  linkedin: https://www.linkedin.com/

# 站点信息
title: 小凡的博客
description: My personal blog
url: http://hiyori.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: hiyori.cn

# disqus 设置
disqus:
  shortname: hiyori

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
